apiVersion: v1
kind: Service
metadata:
  name: tempo-query-frontend
  namespace: observability
spec:
  ports:
    - name: grpc
      port: 9095
      targetPort: 9095
    - name: http
      port: 3100
      targetPort: 3100
  selector:
    app: tempo-query-frontend
