apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-compactor-config
  namespace: observability
data:
  tempo.yaml: |
    compactor:
      compaction:
        block_retention: 1h

    storage:
      trace:
        backend: local
        local:
          path: /var/tempo/blocks
    
