apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-ingester-config
  namespace: observability
data:
  tempo.yaml: |
    ingester:
      trace_idle_period: 10s
      max_block_duration: 5m

    storage:
      trace:
        backend: s3
        s3:
          bucket: twcr-app-logs-grafana-tempo
          endpoint: s3.ap-south-1.amazonaws.com
          region: ap-south-1
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          insecure: false
