apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-querier
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo-querier
  template:
    metadata:
      labels:
        app: tempo-querier
    spec:
      containers:
        - name: tempo
          image: <your-ecr-repo>/tempo:latest
          args:
            - -config.file=/etc/tempo.yaml
            - -target=querier
          volumeMounts:
            - name: config
              mountPath: /etc/tempo.yaml
              subPath: tempo.yaml
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: tempo-s3-creds
                  key: S3_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: tempo-s3-creds
                  key: S3_SECRET_KEY
      volumes:
        - name: config
          configMap:
            name: tempo-querier-config