apiVersion: v1
kind: Service
metadata:
  name: tempo-distributor
  namespace: observability
spec:
  selector:
    app: tempo-distributor
  ports:
    - name: otlp-http
      port: 4318
      targetPort: 4318
  type: ClusterIP