apiVersion: v1
kind: Service
metadata:
  name: tempo-querier
  namespace: observability
spec:
  selector:
    app: tempo-querier
  ports:
    - name: http
      port: 3100
      targetPort: 3100
  type: ClusterIP