apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-querier-config
  namespace: observability
data:
  tempo.yaml: |
    querier: {}

    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo-logs-testing
          endpoint: s3.ap-south-1.amazonaws.com
          region: ap-south-1
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          insecure: false
