apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-querier-config
  namespace: observability
data:
  tempo.yaml: |
    querier:
      frontend_address: tempo-query-frontend.observability.svc.cluster.local:9095
      query_timeout: 60s
      max_query_length: 24h
      max_query_lookback: 24h
      max_query_parallelism: 32
      max_query_series: 1000000
      max_query_length_per_user: 24h

    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo-logs-testing
          endpoint: s3.ap-south-1.amazonaws.com
          region: ap-south-1
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          insecure: false
