apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-query-frontend-config
  namespace: observability
data:
  tempo.yaml: |
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo-logs-testing
          endpoint: s3.ap-south-1.amazonaws.com
          region: ap-south-1
          insecure: false